# -*- coding: utf-8 -*-

from odoo import models, fields, api
class Plm(models.Model):
    _name='mrp.plm'
    _description='Mrp Plm'
    _inherit=['mrp.plm.activity','mail.thread.cc']
    allow_apply_change=fields.Boolean(readonly=True, string="Afficher les modifications appliquées")
    allow_change_stage=fields.Boolean(readonly=True, string="Autoriser le changement d'étape")
    approval_ids=fields.One2many('mrp.plm.approval','eco_id',help="Validations")
    bom_change_ids=fields.One2many('mrp.plm.bom.change','eco_id',readonly=True,help="Modifications de la nomenclature OMT")
    bom_id=fields.Many2one('mrp.bom',ondelete='set null',help="Nomenclature")
    bom_rebase_ids=fields.One2many('mrp.plm.bom.change','rebase_id',help="Refonte de la nomenclature")
    color = fields.Integer('Couleur')
    company_id=fields.Many2one('res.company','Company',ondelete='set null',help="Societé")
    current_bom_id=fields.Many2one('mrp.bom','Current Bom',ondelete='set null',help="Nouvelle nomenclature")
    display_name=fields.Char(readonly=True,string="Nom affiché")
    displayed_image_attachment_id=fields.Many2one('ir.attachment','Attachment',help="Pièce jointe associée")
    displayed_image_id=fields.Many2one('mrp.document','Image displayed',ondelete='set null',help="Afficher l'image")
    effectivity=fields.Selection([('asap','Asap'),('date','to date')],'Date effective',help="Entrée en vigueur")
    effectivity_date=fields.Date(string="Date d'entrée en vigueur")
    kanban_state=fields.Selection([('normal','Normal'),('done','Done'),('blocked','Blocked')],'Kanban State',readonly=True,help="État kanban")
    message_attachment_count=fields.Integer(readonly=True, string="Nombre de pièces jointes")
    message_channel_ids=fields.Many2many('mail.channel',readonly=True,string="Abonnés (Canaux)")
    message_follower_ids=fields.One2many('mail.followers','res_id',help="Abonnés")
    message_has_error=fields.Boolean(readonly=True,help="Erreur d'envoi du message")
    message_has_error_counter=fields.Integer(readonly=True,string="Nombre d'erreurs")
    message_has_sms_error=fields.Integer(readonly=True,string="Erreur d'envoi SMS")
    message_ids=fields.One2many('mail.message','res_id',help="Messages")
    message_is_follower=fields.Boolean(readonly=True,string="Est un abonné")
    message_main_attachment_id=fields.Many2one('ir.attachment',ondelete='set null',index=True)
    message_needaction=fields.Boolean(readonly=True,string="Nécessite une action")
    message_needaction_counter=fields.Integer(readonly=True,string="Nombre d'actions")
    message_partner_ids=fields.Many2many('res.partner',readonly=True,string="Abonnés (Partenaires)")
    message_unread=fields.Boolean(readonly=True,string="Messages non lus")
    message_unread_counter=fields.Integer(readonly=True,string="Compteur de messages non lus")
    mrp_document_count=fields.Integer(readonly=True,string="Nb. pièces jointes")
    mrp_document_ids=fields.One2many('mrp.document','res_id',help="Pièces jointes")
    name=fields.Char(required=True,string="Référence")
    new_bom_id=fields.Many2one('mrp.bom',ondelete='set null',help="Nouvelles nomenclatures")
    new_bom_revision=fields.Integer(string="Révision de la nomenclature")
    note=fields.Text(string='Internal Notes')
    previous_change_ids=fields.One2many('mrp.plm.bom.change','eco_rebase_id',readonly=True, help="Anciennes modifications de l'OMT")
    priority = fields.Selection([('0', 'Normal'),('1', 'Important'),], default='0', index=True, help="Priority")
    product_tmpl_id = fields.Many2one('product.template', 'Product Template',auto_join=True, ondelete="set null")
    routing_change_ids=fields.One2many('mrp.plm.routing.change','eco_id',readonly=True,help="Modifications de l'acheminement OMT")
    stage_id=fields.Many2one('mrp.plm.stage',ondelete='restrict',help="Etape")
    state=fields.Selection([('confirmed','Confirmed'),('progress','Progress'),('rebase','Rebase'),('conflict','Conflict'),('done','Done')],'Status',required=True,readonly=True,help="Statut")
    tag_ids=fields.Many2many('mrp.plm.tag','Tag',string="Étiquettes")
    type=fields.Selection([],'Appliqué sur',required=True,help="Appliqué sur")
    type_id=fields.Many2one('mrp.plm.type','Type',ondelete='restrict',required=True,help="Type")
    user_can_approve=fields.Boolean(readonly=True,string="Peut Approuver")
    user_can_reject=fields.Boolean(readonly=True,string="Peut Refuser")
    user_id=fields.Many2one('res.users','Responsable',ondelete='set null',help="responsable")
    website_message_ids=fields.One2many('mail.message','res_id',help="Messages du site web")